TRUNCATE TABLE [dbo].[Country]
TRUNCATE TABLE [dbo].[Description]
TRUNCATE TABLE [dbo].[Location]
TRUNCATE TABLE [dbo].[Name]
TRUNCATE TABLE [dbo].[Note]
TRUNCATE TABLE [dbo].[Region]
TRUNCATE TABLE [dbo].[State]
TRUNCATE TABLE [dbo].[Town]
TRUNCATE TABLE [dbo].[Type]
TRUNCATE TABLE [dbo].[Url]
TRUNCATE TABLE [dbo].[Castle]

SELECT * FROM [dbo].[Country]
SELECT * FROM [dbo].[Description]
SELECT * FROM [dbo].[Location]
SELECT * FROM [dbo].[Name]
SELECT * FROM [dbo].[Note]
SELECT * FROM [dbo].[Region]
SELECT * FROM [dbo].[State]
SELECT * FROM [dbo].[Town]
SELECT * FROM [dbo].[Type]
SELECT * FROM [dbo].[Url]
SELECT * FROM [dbo].[Castle]