name: Build and Test .NET Desktop Solution with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Docker works on Ubuntu nicely

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore ./CastleRealm.sln

      - name: Build solution
        run: dotnet build ./CastleRealm.sln --configuration Release --no-restore

      - name: Build Docker Image for API
        run: |
          docker build -t api-image ./Api  # Build the Docker image for your API

      - name: Run Docker Container
        run: |
          docker run -d -p 5000:80 --name api-container api-image  # Run the API container in detached mode

      - name: Run unit tests (excluding API tests)
        run: |
          dotnet test ./UnitTests/UnitTests.csproj --configuration Release --no-build --filter "FullyQualifiedName!=Namespace.ApiSmokeTests"

      - name: Run API smoke tests (optional)
        run: |
          dotnet test ./UnitTests/UnitTests.csproj --configuration Release --no-build --filter "FullyQualifiedName==Namespace.ApiSmokeTests"
        env:
          API_URL: http://localhost:5000  # You can pass the API URL to the tests if needed

      - name: Stop Docker container
        run: docker stop api-container  # Clean up by stopping the API container

      - name: Remove Docker container
        run: docker rm api-container  # Clean up by removing the container
